// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numTimes = Integer.parseInt(args[0]);
		int countLessHalf = 0;
		int countMoreHalf = 0;
		for (int i = 1; i <= numTimes; i++){
			if(Math.random() > 0.5){
				countMoreHalf++;
			} else {
				countLessHalf++;
			}
		}
		System.out.println("> 0.5: " +countMoreHalf+ " times");
		System.out.println("<= 0.5: " +countLessHalf+ " times");
		if (countLessHalf > 0){
			System.out.println("Ratio: " +(double)countMoreHalf/countLessHalf);
		}
	}
}